version: "3"

services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    image: ${app-hello-tag}
  auth:
    image: beevelop/nginx-basic-auth
    ports:
      - 8000:80
    links:
      - web