version: "3"

services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    image: dcmpacr.azurecr.io/app-hello:latest
  auth:
    image: beevelop/nginx-basic-auth
    ports:
      - 8000:80
    links:
      - web