name: Terraform Destroy

on:
  delete:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.28
      - name: Terraform Init
        run: terraform init -backend-config="container_name=${{ secrets.TF_CONTAINER_NAME }}" -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT_NAME }}" -backend-config="access_key=${{ secrets.TF_ACCESS_KEY }}" -backend-config="key=${GITHUB_EVENT_REF##*/}.tfstate"
        working-directory: terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
      - name: Terraform Destroy
        if: github.ref != 'refs/heads/master'
        run: terraform destroy -var "acr_admin_username=${{ secrets.DOCKER_USERNAME }}" -var "acr_admin_password=${{ secrets.DOCKER_PASSWORD }}" -var "acr_domain=${{ secrets.DOCKER_REGISTRY }}" -var "environment=${GITHUB_EVENT_REF##*/}" -var "app-hello-tag=${{ secrets.DOCKER_REGISTRY }}/app-hello:${{ github.run_id }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: terraform
